### ISSUE TITLE
Erro ao executar script do robot framework

### ISSUE THREAD

**Issue by davidsonjsantos** [AgileTesters/forum#120]
Instalei o Robot Framework no Linux. Instalei a versão Python 3.8 (Python 3.8.5) e pip3 (pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)). Instalei a Library robotframework-selenium2library.
Quando fui executar o script, utilizei o comando robot nomearquivo.robot, mas retornou esse erro: **zsh: command not found: robot**.

Alguém já passou por isso?

**Comment by lucasjct** [comment]
@davidsonjsantos, nunca tive esse problema. Ocorre também quando você tenta rodar no Bash? Mas eu tentaria reinstalar o Robot usando a virutalenv (simula um ambiente virtual Python sem depender/comprometer o Python do seu sistema operacional). Nao sei se ajuda, mas ficaria assim...

* mkdir meu-diretório && cd meu-diretório.  

##### Seguir o restante dentro do seu diretório 
* Python3 -m venv .venv
* source .venv/bin/activate  
##### Instalando o Robot na Venv *dentro do diretório*.
* pip install robotframework
* pip install robotframework-selenium2library
* pip freeze (verificar se as libs foram instaladas)
#### Rodar o robot (dentro do diretório do seu projeto( .venv deve estar ativada)
robot meuteste.robot
