### ISSUE TITLE
Comparar projeto Figma x Site

### ISSUE THREAD

**Issue by allanocosta** [AgileTesters/forum#131]
Olá a todos!

Queria saber se alguém conhece alguma ferramenta(extensão, site, software) que compare o projeto do Figma com o site desenvolvido.

**Comment by leoGalani** [comment]
Olha... eu particularmente desaconselho a você seguir nesse caminho de cara crachá de projeto de UI.
Nem sempre as coisas fical pixel perfect e o time tem que entender isso.
E outra coisa é que uma coisa tao simples de se testar que automatizar isso é meio que perca de tempo

Dito isso vc pode exportar em png o projeto do figma e tentar usar alguma coisa tipo opencv ou alguma das ferramentas de validação de screenshots --> https://gist.github.com/cvrebert/adf91e429906a4d746cd

**Comment by samycici** [comment]
Se tem abertura pra usar alguma ferramenta paga, tem o https://percy.io/ mas ele não compara do figma também, você vai rodar ele batendo no próprio site, manualmente vc precisa verificar se tá tudo ok e estabelecer os baselines, e aí nas próximas execuções ele sempre vai tirar o screenshot atual e comparar com esse baseline, ele integra no github tb, então dá pra rodar automaticamente a cada Pull Request

**Comment by allanocosta** [comment]
Segui as dicas e com o percy estou conseguindo progredir bastante.
Obrigado pelas dicas!
