### ISSUE TITLE
Erro na execução de testes no plugin cypress-cucumber-preprocessor

### ISSUE THREAD

**Issue by allanocosta** [AgileTesters/forum#162]
Olá,
estou aprendendo a criar testes com o Cypress e queria saber se alguém consegue me ajudar a resolver este erro ao tentar executar uma feature?

Estou usando o cypress-cucumber-preprocessor.

Quando executo uma feature com apenas um teste, o erro não ocorre.

**Title:** Error running plugin

**Message:** The following error was thrown by a plugin. We stopped running your tests because a plugin crashed. Please check your plugins file (`C:\Users\allan\Documents\GitHub\base_cypress-master\cypress\plugins\index.js`)

**Details:** CompositeParserException: Parser errors:
(24:1): expected: #EOF, #TableRow, #TagLine, #ExamplesLine, #ScenarioLine, #ScenarioOutlineLine, #Comment, #Empty, got 'Feature: Calculo de frete da PDP'
(26:5): expected: #EOF, #TableRow, #TagLine, #ExamplesLine, #ScenarioLine, #ScenarioOutlineLine, #Comment, #Empty, got 'Como usuario, eu quero acessar a PDP do produto LC27RG50FQLXZD'
(27:5): expected: #EOF, #TableRow, #TagLine, #ExamplesLine, #ScenarioLine, #ScenarioOutlineLine, #Comment, #Empty, got 'Para poder realizar o calculo do frete para o CEP 26.261-220'
(43:1): expected: #EOF, #TableRow, #TagLine, #ExamplesLine, #ScenarioLine, #ScenarioOutlineLine, #Comment, #Empty, got 'Feature: Adiciona um produto ao carrinho via PDP'
(45:5): expected: #EOF, #TableRow, #TagLine, #ExamplesLine, #ScenarioLine, #ScenarioOutlineLine, #Comment, #Empty, got 'Como usuario, eu quero acessar a PDP do produto LC27RG50FQLXZD'
(46:5): expected: #EOF, #TableRow, #TagLine, #ExamplesLine, #ScenarioLine, #ScenarioOutlineLine, #Comment, #Empty, got 'Para poder adiciona-lo ao carrinho de compras'
    at Function.Errors.CompositeParserException.create (C:\Users\allan\Documents\GitHub\base_cypress-master\node_modules\gherkin\lib\gherkin\errors.js:27:13)
    at Parser.parse (C:\Users\allan\Documents\GitHub\base_cypress-master\node_modules\gherkin\lib\gherkin\parser.js:72:45)
    at module.exports (C:\Users\allan\Documents\GitHub\base_cypress-master\node_modules\cypress-cucumber-preprocessor\lib\loader.js:29:33)
    at Stream.end (C:\Users\allan\Documents\GitHub\base_cypress-master\node_modules\cypress-cucumber-preprocessor\lib\index.js:24:18)
    at _end (C:\Users\allan\Documents\GitHub\base_cypress-master\node_modules\through\index.js:65:9)
    at Stream.stream.end (C:\Users\allan\Documents\GitHub\base_cypress-master\node_modules\through\index.js:74:5)
    at DestroyableTransform.onend (C:\Users\allan\Documents\GitHub\base_cypress-master\node_modules\readable-stream\lib\_stream_readable.js:577:10)
    at Object.onceWrapper (events.js:421:28)
    at DestroyableTransform.emit (events.js:327:22)
    at endReadableNT (C:\Users\allan\Documents\GitHub\base_cypress-master\node_modules\readable-stream\lib\_stream_readable.js:1010:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Stack trace:**
```
Error: The following error was thrown by a plugin. We stopped running your tests because a plugin crashed. Please check your plugins file (`C:\Users\allan\Documents\GitHub\base_cypress-master\cypress\plugins\index.js`)
    at Object.get (C:\Users\allan\AppData\Local\Cypress\Cache\6.2.1\Cypress\resources\app\packages\server\lib\errors.js:961:15)
    at EventEmitter.handleError (C:\Users\allan\AppData\Local\Cypress\Cache\6.2.1\Cypress\resources\app\packages\server\lib\plugins\index.js:159:20)
    at EventEmitter.emit (events.js:315:20)
    at ChildProcess.<anonymous> (C:\Users\allan\AppData\Local\Cypress\Cache\6.2.1\Cypress\resources\app\packages\server\lib\plugins\util.js:19:22)
    at ChildProcess.emit (events.js:315:20)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)

```

**Comment by giselerosa** [comment]
Olá @allanocosta , para eu conseguir te ajudar de uma melhor forma, você conseguiria compartilhar o arquivo feature? Pois aparentemente existe alguma palavra do Gherkin ou sintaxe que está quebrando o plugin.

Outra informação importante:

Qual versão do Cypress você está utilizando?

**Comment by allanocosta** [comment]
> Olá @allanocosta , para eu conseguir te ajudar de uma melhor forma, você conseguiria compartilhar o arquivo feature? Pois aparentemente existe alguma palavra do Gherkin ou sintaxe que está quebrando o plugin.
> 
> Outra informação importante:
> 
> Qual versão do Cypress você está utilizando?

Olá @giselerosa ,
segue as informações do meu arquivo .feature
Estou usando o Cypress na versão 6.2.1
```
@DesafioAutomacao
Feature: Login site Samsung

    Como usuario, eu quero realizar o login com sucesso na loja Samsung

    Background: Acessar a home do site Shop Samsung e fechar a notificao e cookies
        Given usuario acessa o site Shop Samsung
        And usuario fecha o banner de notificacoes se estiver visivel
        And usuario fecha o banner de cookies se estiver visivel

    @LoginCorreto
    Scenario Outline: Logar no site Shop Samsung e visualizar o Menu My Accont
        When usuario clica no botao Account
        And usuario informa um email <email> correto
        And usuario informa uma senha <senha> correta
        When usuario clica no botao Entrar
        Then usuario visualiza o menu do My Account

        Examples:
            | email                   | senha        |
            | EDITADO@EDITADO.COM | EDITADO |

Feature: Calculo de frete da PDP

    Como usuario, eu quero acessar a PDP do produto LC27RG50FQLXZD
    Para poder realizar o calculo do frete para o CEP 26.261-220

    @CalculoFreteCorreto
    Scenario Outline: Acessar a PDP du produto LC27RG50FQLXZD e calcular o frete para o CEP 26261220
        When usuario vai na categoria <categoria>
        And usuario vai na subcategoria <subCategoria>
        And usuario clica na sub subcategoria <subSubCategoria>
        When usuario clica no produto <productEan> da galeria
        When usuario informa um codigo postal <codPostal> para calcular o frete
        And usuario clica no botao calcular
        Then usuario devera visualizar o resultado do calculo

        Examples:
            | categoria   | subCategoria | subSubCategoria | productEan     | codPostal |
            | Informática | Monitores    | Monitor Gamer   | LC27RG50FQLXZD | 26261220  |

Feature: Adiciona um produto ao carrinho via PDP

    Como usuario, eu quero acessar a PDP do produto LC27RG50FQLXZD
    Para poder adiciona-lo ao carrinho de compras

    @AddProdCartPdp
    Scenario Outline: Adicionar o produto LC27RG50FQLXZD no carrinho de compras via PDP
        When usuario vai na categoria <categoria>
        And usuario vai na subcategoria <subCategoria>
        And usuario clica na sub subcategoria <subSubCategoria>
        When usuario clica no produto <productEan> da galeria
        And usuario clica em adicionar ao carrinho
        Then usuario devera visualizar o produto no carrinho de compras

        Examples:
            | categoria   | subCategoria | subSubCategoria | productEan     |
            | Informática | Monitores    | Monitor Gamer   | LC27RG50FQLXZD |
```

**Comment by giselerosa** [comment]
@allanocosta A questão que está gerando o erro é a seguinte.

O arquivo no formato .feature ele espera que tenha somente uma Funcionalidade, e dentro de uma funcionalidade você pode ter 1 ou mais cenários de testes. Sendo assim , o que será necessário que você faça é criar diferentes arquivos para as diferentes Funcionalidades que está testando.  

No seu caso você precisaria criar um outro arquivo para a funcionalidade Feature: Calculo de frete da PDP , e um outro para Feature: Adiciona um produto ao carrinho via PDP.

Experimenta efetuar esse ajuste , e em caso de alguma dúvida estarei aqui.

**Comment by allanocosta** [comment]
> @allanocosta A questão que está gerando o erro é a seguinte.
> 
> O arquivo no formato .feature ele espera que tenha somente uma Funcionalidade, e dentro de uma funcionalidade você pode ter 1 ou mais cenários de testes. Sendo assim , o que será necessário que você faça é criar diferentes arquivos para as diferentes Funcionalidades que está testando.
> 
> No seu caso você precisaria criar um outro arquivo para a funcionalidade Feature: Calculo de frete da PDP , e um outro para Feature: Adiciona um produto ao carrinho via PDP.
> 
> Experimenta efetuar esse ajuste , e em caso de alguma dúvida estarei aqui.

@giselerosa excluí as features e deixei os cenários e agora consigo executar a feature.
Obrigado pela dica!
