### ISSUE TITLE
Simular webcam para captura de foto em teste automatizado

### ISSUE THREAD

**Issue by alexisklaser** [AgileTesters/forum#183]
Oi pessoal, boa tarde

Tenho uma funcionalidade em determinado sistema que captura a foto de uma pessoa pela webcam e armazena ela em um servidor. Posteriormente, esta foto armazenada é utilizada para validar acessos (registros de ponto) que a pessoa faz via reconhecimento facial.

Estou fazendo um estudo para tentar criar um teste automatizado disso.

---

Seriam duas etapas então:

1) Capturar/armazenar a foto no servidor.

2) Submeter uma foto e comparar com a foto armazenada para que o reconhecimento facial seja feito.

---

Alguém já fez algo parecido, conhece algum site que simula uma captura de foto por webcam ou teria alguma dica em geral?

Abs!

**Comment by leoGalani** [comment]
Olá,

Acredito que vc não precise de uma camera de fato para poder testar esse tipo de solução (a não ser que a camera seja proprietária e seu software utilize alguma api especifica da camera).


Para isso, você e ou seu time podem escrever teste de componente (reconhecimento facial) que suba esse serviço e dependendo como for o seu sistema (se precisa treinar antes para reconhecer que foto x é de pessoa x OU se valida que todas as pessoas nas fotos sao a mesma pessoa) vc faz um data driven test com diversas possibilidades.

Falando assim parece simples mas envolve varias descobertas que vc tem que fazer em conjunto com seu time :)

Boa sorte e depois conta como está sendo seu projeto!
