### ISSUE TITLE
Como configurar cucumber-preprocessor + allure report  no plugins\index.js no cypress

### ISSUE THREAD

**Issue by allanocosta** [AgileTesters/forum#188]
Olá pessoal, tudo bem?
Como eu devo configurar o index.js para usar o cucumber-preprocessor + allure report?

Meu arquivo index.js está assim:
```js
//cucumber-preprocessor
const cucumber = require('cypress-cucumber-preprocessor').default

module.exports = (on, config) => {
  on('file:preprocessor', cucumber())
}

//allure report
module.exports = (on, config) => {
    on('file:preprocessor', webpackPreprocessor);
    allureWriter(on, config);
    return config;
};
```
Qual a forma correta de configura-lo?
Se alguém puder exolicar além de dizer a configuração, seria grato.
Nos artigos que encontrei não ficou claro como deve ser.

**Comment by giselerosa** [comment]
Olá @allanocosta você precisará ajustar algumas coisas, que vou listar e tentar explicar o motivo/necessidade.

1 - Primeiramente será necessário você importar o plugin do allure assim como fez com o cucumber.

`const allureWriter = require('@shelex/cypress-allure-plugin/writer');`

Você pode ver mais detalhes na [documentação](https://www.npmjs.com/package/@shelex/cypress-allure-plugin) do plugin 

2 - Será necessário também que a exportação do plugin e ali no código você fez parte correta, mas como você criou uma constante "cucumber" para ser o seu preprocessor, você terá que ajustar no código o "webPreprocessor" para o nome da sua constante , dessa forma:

```
module.exports = (on, config) => {
    on('file:preprocessor', cucumber());
    allureWriter(on, config);
    return config;
};
```

Experimente fazer esse ajuste e veja se assim já funciona. Caso tenha mais alguma dúvida só falar.

**Comment by allanocosta** [comment]
Olá @giselerosa,
Obrigado pela ajuda. Consegui configurar tudo e agora o Allure está funcionando.
