### ISSUE TITLE
Validar elemento não visível na página | cypress

### ISSUE THREAD

**Issue by allanocosta** [AgileTesters/forum#189]
Olá pessoal,
como eu faço para verificar se um elemento não está visível na página com o cypress?

Quando eu usava o selelium eu usava o `findElements(by).size() > 0;`, no cypress eu faço como?

**Comment by rafaelcs** [comment]
@allanocosta Veja essa resposta: https://github.com/cypress-io/cypress/issues/9348#issuecomment-827123205. Neste caso, voce pode criar algo como:

```
assertNonVisibilityOf(locator) {
    return cy.get(locator).should("not.be.visible");
}
```

**Comment by allanocosta** [comment]
@rafaelcs obrigado pela ajuda. Ajudou muito com este comando!
