### ISSUE TITLE
Executar click enquanto visível no Cypress

### ISSUE THREAD

**Issue by allanocosta** [AgileTesters/forum#190]
Olá, aqui estou eu tentando aprender mais sobre o cypress e recorrendo a ajuda de vocês.

No carrinho de compras do site da Electrolux, eu quero clicar em remover o item do carrinho até que o mesmo esteja vazio.

Qual lógica eu posso usar neste caso?

![image](https://user-images.githubusercontent.com/73409778/118004650-050d1180-b320-11eb-82af-cd9744960436.png)

**Comment by rafaelcs** [comment]
@allanocosta tente isso:

```
deleteAllProducts() {
    cy.get(locator).each(($icon) => {
        const iconSize = $icon.length;
        if (iconSize === 0) {
            return false;
        } else {
            cy.wrap($icon).click({force: true});
            cy.get(locator).click();
        }
    })
}
```

**Comment by allanocosta** [comment]
@rafaelcs ele está fazendo o primeiro click e removendo o item, mas depois da erro.
Tentei fazendo um `do while` e tirando o `cy.get(locator).click();` , mas dá erro informando que o elemento não está no DOM.

![image](https://user-images.githubusercontent.com/73409778/118020959-1d395c80-b331-11eb-8b54-ae661899efa6.png)

**Comment by allanocosta** [comment]
@rafaelcs consegui fazer desta forma.
Tive que adicionar um reload. Parece que o cypress estva tentando clicar sempre no primeiro botão.
```
clear_cart() {
  cy.get(locator).each($el => {
    let index = $el.length;
    for(let n=0; n < index; n ++){
      cy.xpath(locator).click({force: true});
      cy.reload()
      };
    })
  };
